services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        volumes:
            - D:/PHP_Project/Trevel/test:/var/www/html
        entrypoint: ["/bin/sh", "-c", "sleep 30 && php-fpm"]
        networks:
            - laravel_network


    nginx:
        image: nginx:latest
        container_name: nginx_container
        restart: always
        ports:
            - "80:80"



        volumes:
            - D:/PHP_Project/Trevel/test/public:/var/www/html/public
            - D:/PHP_Project/Trevel/test/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    mysql_data:

networks:
    laravel_network:
        driver: bridge



